version: "3"
services:
  web:
    build:
      context: code
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: web
    networks:
      - default
      - fraudbnb_network

networks:
   fraudbnb_network:
